name: Publish NPM larvit lib

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm ci
        - run: npm run build --if-present
        - uses: JS-DevTools/npm-publish@v2
          with:
            token: ${{ secrets.NPM_TOKEN }}
