# larvit lib test action with mariadb dependency

name: Test larvit lib with mariadb

on:
  workflow_call:
    inputs:
      mariadb_version:
        type: string
        default: '10.7'

jobs:
  test:
    runs-on: ubuntu-latest

    # Set DB settings in both env variables and db_test.json (below)
    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: test
      DB_PORT: 3306
      DB_DATABASE: test

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mariadb version: ${{ inputs.mariadb_version }}
        mysql database: 'test'
        mysql root password: 'test'
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - shell: bash
      run: |
        cat << EOF > ./config/db_test.json
        {
          "connectionLimit": 10,
          "host": "127.0.0.1",
          "port": 3306,
          "user": "root",
          "password": "test",
          "charset": "utf8mb4_general_ci",
          "supportBigNumbers": true,
          "database": "test"
        }
        EOF
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
